### ISSUE TITLE
TypeError: sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by macanv** [panyang/Wikipedia_Word2vec#1]
while process one text of wiki, the text reading from data is byte type, but the source code use ' '.join(),this line of code will throw an error.
if you like ,you would use follow code instead that:
output.write(space.join(map(bytes.decode, text)) + '\n')

**Comment by panyang** [comment]
That's python3.x problem, just update to the new version:

https://github.com/panyang/Wikipedia_Word2vec/commit/11aab9845c4c6455bf04bc9baf98f17fc5c15bf7

**Comment by panyang** [comment]
close it
